name: Build Android APK

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Install required build dependencies for autotools
      - name: Install build dependencies
        run: sudo apt-get update && sudo apt-get install -y autoconf automake libtool

      # (Optional) Install other dependencies your project needs
      # - name: Install Python and pip dependencies
      #   run: |
      #     python -m pip install --upgrade pip
      #     pip install buildozer

      # Your existing build steps (example)
      - name: Build APK with Buildozer
        run: buildozer android debug

      # Add other workflow steps as needed (e.g., upload artifacts)