name: Build Android APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential ccache openjdk-17-jdk unzip git python3-pip zip zlib1g-dev \
            libffi-dev libssl-dev libjpeg-dev autoconf automake libtool pkg-config m4
          pip install --upgrade pip
          pip install buildozer cython virtualenv

      - name: Buildozer Init + Accept SDK License
        run: |
          buildozer android update
          yes | ~/.buildozer/android/platform/android-sdk/cmdline-tools/latest/bin/sdkmanager --licenses
          ~/.buildozer/android/platform/android-sdk/cmdline-tools/latest/bin/sdkmanager \
            "build-tools;34.0.0" "platform-tools" "platforms;android-34"

      - name: Ensure build-tools are in place
        run: |   
          BUILD_TOOLS_DIR=~/.buildozer/android/platform/android-sdk/build-tools/34.0.0
            if [ ! -d "$BUILD_TOOLS_DIR" ]; then
            mkdir -p ~/.buildozer/android/platform/android-sdk/build-tools
            ln -s ~/.buildozer/android/platform/android-sdk/cmdline-tools/latest/build-tools/34.0.0 "$BUILD_TOOLS_DIR"
            fi


      - name: Build APK
        run: |
          buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: FolderLocker-APK
          path: bin/*.apk
