
name: Build Android APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install buildozer & dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential ccache openjdk-17-jdk unzip git python3-pip zip zlib1g-dev libffi-dev libssl-dev
          pip install buildozer cython virtualenv

      - name: Install SDK Build Tools & platform-tools
        run: |
            yes | buildozer android update
        

      - name: Install AIDL tools
        run: |
            yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses
            $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager "build-tools;34.0.0" "platform-tools"
        

      - name: Build APK
        run: |
          buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: FolderLockerS-APK
          path: bin/*.apk
